#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sat Feb 07 18:47:01 CST 2026
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim testbench8_behav -key {Behavioral:sim_1:Functional:testbench8} -tclbatch testbench8.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log"
xsim testbench8_behav -key {Behavioral:sim_1:Functional:testbench8} -tclbatch testbench8.tcl -protoinst "protoinst_files/design_1.protoinst" -log simulate.log

